"""Pre-defined demo lists for fixed demo mode (optional).

This file provides fixed demo lists for each prompt type.
These are used when demo_method='fixed' in the environment variables.
"""

# Propose demos - for proposing word candidates
list_propose_demos = [
    {"input": "Current Board:\n_HO__\nWIRRA\nAVAIL\n_ET__\nTREED\n\nUnfilled:\nv1. _WA_T -- Swarthy; tawny\n\nv4. _RI_E -- To indite; to scribble\n\nh1. _HO__ -- Presented; revealed\n\nh4. _ET__ -- A cigarette\n\nv5. _AL_D -- An insecticide\n\nFilled:\nv3. ORATE -- To speak formally\n\nv2. HIVER -- An apiarist or bee keeper\n\nh2. WIRRA -- An interjection expressing sorrow\n\nh3. AVAIL -- Benefit; result\n\nh5. TREED -- Chased up a tree\n\nChanged:\n", "output": "v1. swart (certain)\nv4. write (certain)\nh1. shown (certain)\nh4. rette (medium)\nv5. naled (certain)"},
{"input": "Current Board:\n_HO__\nWIRRA\nAVAIL\n_ET__\nTREED\n\nUnfilled:\nh4. _ET__ -- A cigarette\n\nv5. _AL_D -- An insecticide\n\nv1. _WA_T -- Swarthy; tawny\n\nh1. _HO__ -- Presented; revealed\n\nv4. _RI_E -- To indite; to scribble\n\nFilled:\nv2. HIVER -- An apiarist or bee keeper\n\nh5. TREED -- Chased up a tree\n\nh3. AVAIL -- Benefit; result\n\nh2. WIRRA -- An interjection expressing sorrow\n\nv3. ORATE -- To speak formally\n\nChanged:\n", "output": "h1. shown (certain)\nh4. rette (medium)\nv1. swart (certain)\nv4. write (certain)\nv5. naled (certain)"},
{"input": "Current Board:\n____G\nRIMER\nOMBRE\nAMATI\nKARST\n\nUnfilled:\nv4. _ERTS -- An interjection expressing exasperation; nonsense\n\nv2. _IMMA -- A semitone\n\nh1. ____G -- To hold onto\n\nv3. _MBAR -- To exclude\n\nv1. _ROAK -- A frog sound; to die\n\nFilled:\nv5. GREIT -- To greet; to weep\n\nh4. AMATI -- A violin\n\nh2. RIMER -- An enlarged tool\n\nh5. KARST -- A limestone region marked by sinks, abrupt ridges, protuberant rocks\n\nh3. OMBRE -- Shaded or dyed; a 3 person card game using 40 cards\n\nChanged:\n", "output": "h1. cling (certain)\n\nv1. croak (certain)\n\nv2. limma (high)\n\nv3. imbar (medium) \u2014 (possible alternatives: embar (low), umbar (low))\n\nv4. nerts (certain)"},
{"input": "Current Board:\n____G\nRIMER\nOMBRE\nAMATI\nKARST\n\nUnfilled:\nv4. _ERTS -- An interjection expressing exasperation; nonsense\n\nv1. _ROAK -- A frog sound; to die\n\nv2. _IMMA -- A semitone\n\nh1. ____G -- To hold onto\n\nv3. _MBAR -- To exclude\n\nFilled:\nh3. OMBRE -- Shaded or dyed; a 3 person card game using 40 cards\n\nv5. GREIT -- To greet; to weep\n\nh2. RIMER -- An enlarged tool\n\nh4. AMATI -- A violin\n\nh5. KARST -- A limestone region marked by sinks, abrupt ridges, protuberant rocks\n\nChanged:\n", "output": "h1. CLING (certain)\nv1. CROAK (certain)\nv2. LIMMA (high)\nv3. IMBAR (medium)\nv4. NERTS (certain)"},
{"input": "Current Board:\nFRAPE\n_EBA_\n_MOL_\n_IMA_\nSTARN\n\nUnfilled:\nh3. _MOL_ -- An agave root used as a substitute for soap\n\nv1. F___S -- Insect droppings\n\nh2. _EBA_ -- To bat again\n\nh4. _IMA_ -- A scarf; a cymar; a loose dress\n\nv5. E___N -- Eternal, everlasting\n\nFilled:\nv2. REMIT -- To replace; to diminish; to release; to pay\n\nh5. STARN -- A star; the buttocks\n\nh1. FRAPE -- A crowd; a mob\n\nv3. ABOMA -- A South American boa constrictor\n\nv4. PALAR -- Resembling a stake\n\nChanged:\n", "output": "h2. REBAT (certain)\nh3. AMOLE (certain)\nh4. SIMAR (certain)\nv1. FRASS (certain)\nv5. ETERN (certain)"}
]

# If-correct demos - for validating word-meaning pairs
list_if_correct_demos = [
    {"input": "Word: \"SKALD\", Meaning: \"Scald; an ancient Scandinavian bard\"", "output": "No"},
{"input": "Word: \"WATER\", Meaning: \"H2O; to irrigate\"", "output": "Yes"},
{"input": "Word: \"PONGA\", Meaning: \"A New Zealand tree fern\"", "output": "Yes"},
{"input": "Word: \"TOYER\", Meaning: \"A trifler\"", "output": "Yes"},
{"input": "Word: \"KAROO\", Meaning: \"A South African dry plateau\"", "output": "Yes"}
]

# Suggest demos - for generating improvement suggestions
list_suggest_demos = [
    {"input": "Current Board:\nSKALD\nWATER\nERODE\nPONGA\nTOYER\n", "output": "Review the grid crossings to locate which letters force the incorrect vertical word DREAR and mark those conflicting cells. Re-evaluate the clue for v5 against crossing letters and replace DREAR with a five-letter candidate that fits both the clue and the existing horizontal answers. Check each horizontal and vertical entry against the clue definitions to ensure no subtle misreads (alternate spellings, obscure words). Use a dictionary or crossword wordlist to confirm candidate words before committing them to the grid. After placing replacements, re-scan the entire board for consistency and adjust any remaining mismatches."},
{"input": "Current Board:\nSKALD\nWATER\n_RODE\n_ONGA\nTOYER\n", "output": "Start by filling the confirmed across answers first and mark their intersecting letters to constrain vertical options. Use the known vertical clue definitions and the existing letters to enumerate 5-letter candidates that fit each pattern. Prioritize high-frequency letter placements (vowels in middle positions, common consonant pairs) and eliminate words that conflict with any confirmed across letters. If multiple candidates remain, cross-check each against all intersecting words before committing. Keep a short list of plausible words for each slot and iterate until all five-letter entries are consistent."},
{"input": "Current Board:\nSKALD\nWATER\n_ROD_\nPONGA\nTOYER\n", "output": "Re-evaluate h1 and replace SKALD with a valid 5-letter entry that fits the confirmed vertical letters.  \nUse the confirmed verticals (v2 KAROO, v3 ATONY, v4 LEDGE) to deduce intersecting letters and constrain horizontal options.  \nFor h3 (_ROD_), test candidates like BROOD or CROWD against the vertical crossings before committing.  \nPrioritize locking all vertical answers first, then fill horizontals to avoid cascading conflicts.  \nVerify each candidate against clue definitions and a dictionary to prevent repeating an incorrect word."},
{"input": "Current Board:\nSKAL_\nWATER\nERODE\nPONG_\nTOYER\n", "output": "Start by listing all clue definitions and confirmed correct words to lock their positions before making changes. Use the intersecting letters from the vertical and horizontal answers to constrain possible replacements for the blank cells. Prioritize filling v1\u2013v4 since their known answers provide strong constraints across multiple rows. When uncertain, generate candidate five-letter words that match both the clue and the fixed cross letters, then test them in the grid. After placing each word, re-check clue definitions and letter consistency to avoid cascading errors."},
{"input": "Current Board:\n_KAL_\nWATER\nERODE\nPONGA\nTOYER\n", "output": "Start by reviewing the full grid and all clue definitions to note which slots are fixed and which need reevaluation.  \nFill the confirmed horizontal words first, then check each intersecting letter against potential vertical answers before committing.  \nFor ambiguous or rare words, consult a reliable word list or dictionary to confirm spelling and meaning.  \nUse the pattern of crosses to eliminate incompatible candidates quickly and prioritize words that fit multiple constraints.  \nIterate with small changes, rechecking all crossings after each replacement until every five-letter word is valid."}
]

# Value demos - for evaluating word feasibility
list_value_demos = [
    {"input": "Current Board:\nFRAPE\n_EBA_\nAMOLE\n_IMA_\nSTARN\n\nUnfilled:\nh2. _EBA_ -- To bat again\n\nv5. E_E_N -- Eternal, everlasting\n\nh4. _IMA_ -- A scarf; a cymar; a loose dress\n\nv1. F_A_S -- Insect droppings\n\nFilled:\nv4. PALAR -- Resembling a stake\n\nv3. ABOMA -- A South American boa constrictor\n\nh5. STARN -- A star; the buttocks\n\nh1. FRAPE -- A crowd; a mob\n\nv2. REMIT -- To replace; to diminish; to release; to pay\n\nh3. AMOLE -- An agave root used as a substitute for soap\n\nChanged:\n", "output": "Here are corrected evaluations and the best matching words:\n\n1) Incorrect; to injure: w _ o _ g\n- Word: wrong \u2014 fits (w r o n g). \"Wrong\" = incorrect; as a verb \"to wrong\" can mean to injure or do injustice to. \n- Verdict: sure\n\n2) A person with an all-consuming enthusiasm, such as for computers or anime: _ _ _ _ u\n- Word: otaku \u2014 fits (o t a k u). \n- Verdict: sure\n\n3) Dewy; roscid: r _ _ _ l\n- I cannot find a common English 5\u2011letter word starting with r and ending with l that specifically means \"dewy\" (roscid). Possible synonyms are moist, dewy, humid, but none match the pattern r _ _ _ l.\n- Verdict: maybe (no common match found)\n\n4) A woodland: _ l _ d e\n- Word: glade \u2014 fits (g l a d e). A glade is an open space in a wood (closely related to woodland context).\n- Verdict: sure\n\n5) An inn: _ d _ w f\n- No English 5\u2011letter word with the pattern _ d _ w f is plausible (English words do not normally end in \"wf\"); no match.\n- Verdict: impossible\n\n6) Chance; a parasitic worm; a fish: w r a k _\n- The intended meanings point to \"fluke\" (chance; a parasitic flatworm; a fish is a fluke), but that is f l u k e and does not match w r a k _. No English word wrak_ matches those senses.\n- Verdict: impossible\n\n7) A crowd; a mob: f r a p e\n- \"Frape\" does not mean crowd or mob. A correct common word for crowd/mob is \"throng\" (6 letters) or \"swarm\" (5 letters), but neither is f r a p e. No match to \"frape.\"\n- Verdict: impossible (for the pattern given)"},
{"input": "Current Board:\nFRAPE\n_EBA_\nAMOLE\n_IMA_\nSTARN\n\nUnfilled:\nh2. _EBA_ -- To bat again\n\nv5. E_E_N -- Eternal, everlasting\n\nh4. _IMA_ -- A scarf; a cymar; a loose dress\n\nv1. F_A_S -- Insect droppings\n\nFilled:\nv4. PALAR -- Resembling a stake\n\nv3. ABOMA -- A South American boa constrictor\n\nh5. STARN -- A star; the buttocks\n\nh1. FRAPE -- A crowd; a mob\n\nv2. REMIT -- To replace; to diminish; to release; to pay\n\nh3. AMOLE -- An agave root used as a substitute for soap\n\nChanged:\n", "output": "Your first two are correct. Here are the rest:\n\n- Dewy; roscid \u2014 pattern r _ _ _ l\n  - Verdict: maybe. I don\u2019t know a common English 5\u2011letter word r----l that means \u201cdewy.\u201d No clear match comes to mind, so it\u2019s possible but not sure.\n\n- A woodland \u2014 pattern _ l _ d e\n  - Verdict: sure. GL ADE (glade) fits the pattern (g l a d e). Note: a glade is a clearing in a wood rather than the whole woodland, but it\u2019s a common relevant word.\n\n- An inn \u2014 pattern _ d _ w f\n  - Verdict: impossible. No English 5\u2011letter word matching _ d _ w f meaning \u201can inn\u201d is known.\n\n- Chance; a parasitic worm; a fish \u2014 pattern w r a k _\n  - Verdict: impossible. No 5\u2011letter English word w r a k _ matches those meanings (the intended word \u201cfluke\u201d does not fit the pattern).\n\n- To bat again \u2014 pattern _ e b a _\n  - Verdict: sure. REBAT (r e b a t) fits the pattern and can mean \u201cto bat again\u201d (re\u2011bat)."},
{"input": "Current Board:\nFRAPE\n_EBA_\nAMOLE\n_IMA_\nSTARN\n\nUnfilled:\nh2. _EBA_ -- To bat again\n\nv5. E_E_N -- Eternal, everlasting\n\nh4. _IMA_ -- A scarf; a cymar; a loose dress\n\nv1. F_A_S -- Insect droppings\n\nFilled:\nv4. PALAR -- Resembling a stake\n\nv3. ABOMA -- A South American boa constrictor\n\nh5. STARN -- A star; the buttocks\n\nh1. FRAPE -- A crowd; a mob\n\nv2. REMIT -- To replace; to diminish; to release; to pay\n\nh3. AMOLE -- An agave root used as a substitute for soap\n\nChanged:\n", "output": "\"Amole\" (a-m-o-l-e) is a valid 5-letter word and does mean an agave/soaproot used as a substitute for soap \u2014 so: sure.\n\n(As a note: for \"A woodland\" with pattern _ l _ d e, \"glade\" fits the pattern but means an open space in a wood rather than the whole woodland.)"},
{"input": "Current Board:\nFRAPE\n_EBA_\nAMOLE\n_IMA_\nSTARN\n\nUnfilled:\nh2. _EBA_ -- To bat again\n\nv5. E_E_N -- Eternal, everlasting\n\nh4. _IMA_ -- A scarf; a cymar; a loose dress\n\nv1. F_A_S -- Insect droppings\n\nFilled:\nv4. PALAR -- Resembling a stake\n\nv3. ABOMA -- A South American boa constrictor\n\nh5. STARN -- A star; the buttocks\n\nh1. FRAPE -- A crowd; a mob\n\nv2. REMIT -- To replace; to diminish; to release; to pay\n\nh3. AMOLE -- An agave root used as a substitute for soap\n\nChanged:\n", "output": "sure \u2014 \"SIMAR\" (s i m a r). A simar (also spelled cymar) is a light scarf-like garment or loose dress."},
{"input": "Current Board:\nFRAPE\n_EBA_\nAMOLE\n_IMA_\nSTARN\n\nUnfilled:\nh2. _EBA_ -- To bat again\n\nv5. E_E_N -- Eternal, everlasting\n\nh4. _IMA_ -- A scarf; a cymar; a loose dress\n\nv1. F_A_S -- Insect droppings\n\nFilled:\nv4. PALAR -- Resembling a stake\n\nv3. ABOMA -- A South American boa constrictor\n\nh5. STARN -- A star; the buttocks\n\nh1. FRAPE -- A crowd; a mob\n\nv2. REMIT -- To replace; to diminish; to release; to pay\n\nh3. AMOLE -- An agave root used as a substitute for soap\n\nChanged:\n", "output": "impossible\n\nThere is no common five\u2011letter English word spelled S T A R N that means both \"a star\" and \"the buttocks.\" The closest plausible word for \"buttocks\"/rear is \"stern\" (S T E R N), but that has an E in position 3, not an A; there is no standard word \"starn\" with the required meanings."}
]

# Note: These lists are empty by default.
# You can populate them with fixed examples if you want to use demo_method='fixed'
# Otherwise, use demo_method='retrieved' or 'reranked' for dynamic retrieval
